add the --duration option

diff --git a/klickly b/klickly
--- a/klickly
+++ b/klickly
@@ -66,8 +66,9 @@ A command-line metronome using lilypond snippets to support arbitrary musical pa
            to the next or previous song.
 
 [options]:
-  -i    Force interactive mode (default, if a terminal appears to be connected).
-  -n    Force non-interactive mode (default, if no terminal appears to be connected).
+  -i             Force interactive mode (default, if a terminal appears to be connected).
+  -n             Force non-interactive mode (default, if no terminal appears to be connected).
+  --duration [s] Time in seconds after which to abort playing the pattern (default: forever).
 
 Further configuration options are available at $CONF."
 exit 1
@@ -139,6 +140,8 @@ local interactive=0
 [ -t 0 ] || interactive=1
 
 #parse options
+local duration=
+local reDuration='^[0-9]+$'
 while : ; do
   case "$1" in
     "-h")
@@ -153,6 +156,12 @@ while : ; do
     "-i")
       interactive=0
       ;;
+    "--duration")
+      [ $# -gt 1 ] || error "Missing seconds argument for the --duration option."
+      duration="$2"
+      [[ "$duration" =~ $reDuration ]] || error "Invalid --duration seconds argument: $duration"
+      shift
+      ;;
     "--")
       shift
       break
@@ -166,6 +175,7 @@ while : ; do
 done
 
 #parse args
+[ $# -ge 1 ] || error "At least the tempo must be specified."
 local tempo="$1"
 local tempoBase="$TEMPO_BASE"
 local token=
@@ -312,9 +322,11 @@ fi
 
 #play MIDI output
 local midiFile="${lyFile%.ly}.midi"
+local add=""
+[ -n "$duration" ] && add="--duration $duration"
 echo "Playing..."
 #NOTE: we cannot use exec as that would remove existing EXIT traps
-"$MIDI2DEV" --loop -c "$SCRIPT_NAME" -f "$midiFile" -a "$MIDI_API" -o "$MIDI_SERVER_PORT" > /dev/null &
+"$MIDI2DEV" --loop $add -c "$SCRIPT_NAME" -f "$midiFile" -a "$MIDI_API" -o "$MIDI_SERVER_PORT" > /dev/null &
 EXIT_TRAP="$EXIT_TRAP ; kill $! &> /dev/null"
 wait $!
 }
@@ -323,14 +335,17 @@ function addToSetlist {
 local title="$1"
 local tempo="$2"
 local file="$3"
+local duration="$4"
 
 [ -z "$title" ] && [ -z "$tempo" ] && [ -z "$file" ] && return 1
 [ -z "$tempo" ] && error "Missing tempo for title: $title, file: $file."
 [ -z "$file" ] && error "Missing file for title: $title, tempo: $tempo."
+#title & duration are optional
 
 SETLIST["${SETLIST_LENGTH}_title"]="$title"
 SETLIST["${SETLIST_LENGTH}_tempo"]="$tempo"
 SETLIST["${SETLIST_LENGTH}_file"]="$file"
+SETLIST["${SETLIST_LENGTH}_duration"]="$duration"
 
 SETLIST_LENGTH=$(( $SETLIST_LENGTH + 1 ))
 }
@@ -339,29 +354,32 @@ function readSetlist {
 local setlist="$1"
 local line=
 local commentRegex='^#.*$'
-local valueRegex='^(title|tempo|file):[[:space:]]*(.*[^[:space:]]+)[[:space:]]*$'
+local valueRegex='^(title|tempo|file|duration):[[:space:]]*(.*[^[:space:]]+)[[:space:]]*$'
 local decimalRegex="^[0-9]+$"
 local title=""
 local tempo=""
+local duration=""
 local file=""
 
 while IFS= read -r line || [ -n "$line" ] ; do
   if [[ "$line" =~ $commentRegex ]] ; then
     continue
   elif [ "$line" == "pause" ] ; then
-    addToSetlist "$PAUSE_TITLE" "1" "$PAUSE_FILE" || continue
+    addToSetlist "$PAUSE_TITLE" "1" "$PAUSE_FILE" "" || continue
 
     #reset
     title=""
     tempo=""
     file=""
+    duration=""
   elif [ -z "$line" ] ; then
-    addToSetlist "$title" "$tempo" "$file" || continue
+    addToSetlist "$title" "$tempo" "$file" "$duration" || continue
 
     #reset
     title=""
     tempo=""
     file=""
+    duration=""
   elif [[ "$line" =~ $valueRegex ]] ; then
     local name="${BASH_REMATCH[1]}"
     local value="${BASH_REMATCH[2]}"
@@ -369,7 +387,10 @@ while IFS= read -r line || [ -n "$line" ] ; do
       title="$value"
     elif [[ "$name" == "tempo" ]] ; then
       tempo="$value"
-      [[ $tempo =~ $decimalRegex ]] || error "Non-decimal tempo: $tempo"
+      [[ "$tempo" =~ $decimalRegex ]] || error "Non-decimal tempo: $tempo"
+    elif [[ "$name" == "duration" ]] ; then
+      duration="$value"
+      [[ "$duration" =~ $decimalRegex ]] || error "Non-decimal duration: $duration"
     elif [[ "$name" == "file" ]] ; then
       file="$value"
     else
@@ -381,7 +402,7 @@ while IFS= read -r line || [ -n "$line" ] ; do
 done < "$setlist"
 
 #add last, if necessary (EOF was reached)
-addToSetlist "$title" "$tempo" "$file"
+addToSetlist "$title" "$tempo" "$file" "$duration"
 
 [ ${#SETLIST[@]} -gt 0 ] || error "The setlist appears to be empty or could not be read."
 
@@ -398,9 +419,10 @@ local index="$1"
 local title="${SETLIST["${index}_title"]}"
 local tempo="${SETLIST["${index}_tempo"]}"
 local file="${SETLIST["${index}_file"]}"
+local duration="${SETLIST["${index}_duration"]}"
 
-#terminate the last playback
-[ -n "$SETLIST_PROCESS" ] && kill "$SETLIST_PROCESS"
+#terminate the last playback (process may not exist anymore, if duration was used)
+[ -n "$SETLIST_PROCESS" ] && kill "$SETLIST_PROCESS" 2> /dev/null
 
 #text to speech synth and the run are executed in a subshell in order not to block user input
 (
@@ -415,7 +437,9 @@ local file="${SETLIST["${index}_file"]}"
   EXIT_TRAP=':'
   trap 'eval $EXIT_TRAP' EXIT
 
-  run -n "$tempo" "$file" < /dev/null
+  local add=""
+  [ -n "$duration" ] && add="--duration $duration"
+  run -n $add "$tempo" "$file" < /dev/null
 ) &
 disown
 SETLIST_PROCESS=$!
